/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PixelWall {
  export type CanvasMetaStruct = {
    width: BigNumberish;
    height: BigNumberish;
    isLocked: boolean;
    createdAt: BigNumberish;
    lockedAt: BigNumberish;
    encryptedStrokeCount: BytesLike;
    lastMetadataCID: string;
  };

  export type CanvasMetaStructOutput = [
    width: bigint,
    height: bigint,
    isLocked: boolean,
    createdAt: bigint,
    lockedAt: bigint,
    encryptedStrokeCount: string,
    lastMetadataCID: string
  ] & {
    width: bigint;
    height: bigint;
    isLocked: boolean;
    createdAt: bigint;
    lockedAt: bigint;
    encryptedStrokeCount: string;
    lastMetadataCID: string;
  };

  export type PixelViewStruct = {
    encryptedColor: BytesLike;
    painter: AddressLike;
    updatedAt: BigNumberish;
  };

  export type PixelViewStructOutput = [
    encryptedColor: string,
    painter: string,
    updatedAt: bigint
  ] & { encryptedColor: string; painter: string; updatedAt: bigint };
}

export interface PixelWallInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_DIMENSION"
      | "STROKE_COOLDOWN"
      | "approve"
      | "balanceOf"
      | "confidentialProtocolId"
      | "createCanvas"
      | "getApproved"
      | "getCanvasMeta"
      | "getCanvasStrokeCount"
      | "getCanvasTokenId"
      | "getPainterContribution"
      | "getPixelColor"
      | "getPixelView"
      | "isApprovedForAll"
      | "lastStrokeAt"
      | "lockCanvas"
      | "mintCanvasNFT"
      | "name"
      | "ownerOf"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setPixel"
      | "supportsInterface"
      | "symbol"
      | "tokenURI"
      | "transferFrom"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "BatchMetadataUpdate"
      | "CanvasCreated"
      | "CanvasLocked"
      | "CanvasMinted"
      | "MetadataUpdate"
      | "PixelUpdated"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_DIMENSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STROKE_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCanvas",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCanvasMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCanvasStrokeCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCanvasTokenId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPainterContribution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPixelColor",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPixelView",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastStrokeAt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockCanvas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCanvasNFT",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPixel",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_DIMENSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STROKE_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCanvas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCanvasMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCanvasStrokeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCanvasTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPainterContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPixelColor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPixelView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastStrokeAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockCanvas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintCanvasNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPixel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchMetadataUpdateEvent {
  export type InputTuple = [
    _fromTokenId: BigNumberish,
    _toTokenId: BigNumberish
  ];
  export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
  export interface OutputObject {
    _fromTokenId: bigint;
    _toTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CanvasCreatedEvent {
  export type InputTuple = [
    canvasId: BigNumberish,
    width: BigNumberish,
    height: BigNumberish,
    creator: AddressLike
  ];
  export type OutputTuple = [
    canvasId: bigint,
    width: bigint,
    height: bigint,
    creator: string
  ];
  export interface OutputObject {
    canvasId: bigint;
    width: bigint;
    height: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CanvasLockedEvent {
  export type InputTuple = [canvasId: BigNumberish, locker: AddressLike];
  export type OutputTuple = [canvasId: bigint, locker: string];
  export interface OutputObject {
    canvasId: bigint;
    locker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CanvasMintedEvent {
  export type InputTuple = [
    canvasId: BigNumberish,
    tokenId: BigNumberish,
    minter: AddressLike,
    metadataCID: string
  ];
  export type OutputTuple = [
    canvasId: bigint,
    tokenId: bigint,
    minter: string,
    metadataCID: string
  ];
  export interface OutputObject {
    canvasId: bigint;
    tokenId: bigint;
    minter: string;
    metadataCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdateEvent {
  export type InputTuple = [_tokenId: BigNumberish];
  export type OutputTuple = [_tokenId: bigint];
  export interface OutputObject {
    _tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PixelUpdatedEvent {
  export type InputTuple = [
    canvasId: BigNumberish,
    x: BigNumberish,
    y: BigNumberish,
    painter: AddressLike,
    encryptedColorHandle: BytesLike
  ];
  export type OutputTuple = [
    canvasId: bigint,
    x: bigint,
    y: bigint,
    painter: string,
    encryptedColorHandle: string
  ];
  export interface OutputObject {
    canvasId: bigint;
    x: bigint;
    y: bigint;
    painter: string;
    encryptedColorHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PixelWall extends BaseContract {
  connect(runner?: ContractRunner | null): PixelWall;
  waitForDeployment(): Promise<this>;

  interface: PixelWallInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_DIMENSION: TypedContractMethod<[], [bigint], "view">;

  STROKE_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createCanvas: TypedContractMethod<
    [width: BigNumberish, height: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getCanvasMeta: TypedContractMethod<
    [canvasId: BigNumberish],
    [
      [PixelWall.CanvasMetaStructOutput, bigint] & {
        meta: PixelWall.CanvasMetaStructOutput;
        tokenId: bigint;
      }
    ],
    "view"
  >;

  getCanvasStrokeCount: TypedContractMethod<
    [canvasId: BigNumberish],
    [string],
    "view"
  >;

  getCanvasTokenId: TypedContractMethod<
    [canvasId: BigNumberish],
    [bigint],
    "view"
  >;

  getPainterContribution: TypedContractMethod<
    [painter: AddressLike],
    [string],
    "view"
  >;

  getPixelColor: TypedContractMethod<
    [canvasId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [string],
    "view"
  >;

  getPixelView: TypedContractMethod<
    [canvasId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [PixelWall.PixelViewStructOutput],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  lastStrokeAt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  lockCanvas: TypedContractMethod<
    [canvasId: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintCanvasNFT: TypedContractMethod<
    [canvasId: BigNumberish, metadataCID: string],
    [bigint],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setPixel: TypedContractMethod<
    [
      canvasId: BigNumberish,
      x: BigNumberish,
      y: BigNumberish,
      encryptedColorExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_DIMENSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STROKE_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createCanvas"
  ): TypedContractMethod<
    [width: BigNumberish, height: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCanvasMeta"
  ): TypedContractMethod<
    [canvasId: BigNumberish],
    [
      [PixelWall.CanvasMetaStructOutput, bigint] & {
        meta: PixelWall.CanvasMetaStructOutput;
        tokenId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCanvasStrokeCount"
  ): TypedContractMethod<[canvasId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCanvasTokenId"
  ): TypedContractMethod<[canvasId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPainterContribution"
  ): TypedContractMethod<[painter: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPixelColor"
  ): TypedContractMethod<
    [canvasId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPixelView"
  ): TypedContractMethod<
    [canvasId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [PixelWall.PixelViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastStrokeAt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockCanvas"
  ): TypedContractMethod<[canvasId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mintCanvasNFT"
  ): TypedContractMethod<
    [canvasId: BigNumberish, metadataCID: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPixel"
  ): TypedContractMethod<
    [
      canvasId: BigNumberish,
      x: BigNumberish,
      y: BigNumberish,
      encryptedColorExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BatchMetadataUpdate"
  ): TypedContractEvent<
    BatchMetadataUpdateEvent.InputTuple,
    BatchMetadataUpdateEvent.OutputTuple,
    BatchMetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "CanvasCreated"
  ): TypedContractEvent<
    CanvasCreatedEvent.InputTuple,
    CanvasCreatedEvent.OutputTuple,
    CanvasCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CanvasLocked"
  ): TypedContractEvent<
    CanvasLockedEvent.InputTuple,
    CanvasLockedEvent.OutputTuple,
    CanvasLockedEvent.OutputObject
  >;
  getEvent(
    key: "CanvasMinted"
  ): TypedContractEvent<
    CanvasMintedEvent.InputTuple,
    CanvasMintedEvent.OutputTuple,
    CanvasMintedEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdate"
  ): TypedContractEvent<
    MetadataUpdateEvent.InputTuple,
    MetadataUpdateEvent.OutputTuple,
    MetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "PixelUpdated"
  ): TypedContractEvent<
    PixelUpdatedEvent.InputTuple,
    PixelUpdatedEvent.OutputTuple,
    PixelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BatchMetadataUpdate(uint256,uint256)": TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;
    BatchMetadataUpdate: TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;

    "CanvasCreated(uint256,uint16,uint16,address)": TypedContractEvent<
      CanvasCreatedEvent.InputTuple,
      CanvasCreatedEvent.OutputTuple,
      CanvasCreatedEvent.OutputObject
    >;
    CanvasCreated: TypedContractEvent<
      CanvasCreatedEvent.InputTuple,
      CanvasCreatedEvent.OutputTuple,
      CanvasCreatedEvent.OutputObject
    >;

    "CanvasLocked(uint256,address)": TypedContractEvent<
      CanvasLockedEvent.InputTuple,
      CanvasLockedEvent.OutputTuple,
      CanvasLockedEvent.OutputObject
    >;
    CanvasLocked: TypedContractEvent<
      CanvasLockedEvent.InputTuple,
      CanvasLockedEvent.OutputTuple,
      CanvasLockedEvent.OutputObject
    >;

    "CanvasMinted(uint256,uint256,address,string)": TypedContractEvent<
      CanvasMintedEvent.InputTuple,
      CanvasMintedEvent.OutputTuple,
      CanvasMintedEvent.OutputObject
    >;
    CanvasMinted: TypedContractEvent<
      CanvasMintedEvent.InputTuple,
      CanvasMintedEvent.OutputTuple,
      CanvasMintedEvent.OutputObject
    >;

    "MetadataUpdate(uint256)": TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;
    MetadataUpdate: TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;

    "PixelUpdated(uint256,uint256,uint256,address,bytes32)": TypedContractEvent<
      PixelUpdatedEvent.InputTuple,
      PixelUpdatedEvent.OutputTuple,
      PixelUpdatedEvent.OutputObject
    >;
    PixelUpdated: TypedContractEvent<
      PixelUpdatedEvent.InputTuple,
      PixelUpdatedEvent.OutputTuple,
      PixelUpdatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
